name: Docker Image CI

on: [repository_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the stack
      working-directory: ./phis-docker
      run: docker-compose up -d
    - name: run_rdf4j
      run:  docker exec -i --user root rdf4j /bin/bash /tmp/seed-data.sh
    - name: run_postgres
      run:  docker exec -i postgres /bin/bash /tmp/seed-data.sh
    - name: run_mvn_verify_VERY_GOOD
      run: docker exec -i -w /home/phis/phis-ws/phis2-ws phis-ws /bin/bash /usr/bin/mvn verify -Pprod
